<a href="https://colab.research.google.com/github/sarmitamajumdar/Alternatives/blob/main/Tensorflow_keras_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Getting Started withKeras-Sequential Model Creation

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# import libraries

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Softmax


### Creating feedforward Model with 3 Layers

In [4]:
model = Sequential([
      Flatten(input_shape=(28,28)),
      Dense(16, activation = "relu"),
      Dense(16, activation = "relu"),
      Dense(10, activation="softmax")
])

### Printing Model Summary with wight and summary

In [5]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(784, 16) dtype=float32, numpy=
 array([[ 0.0144347 , -0.07550099,  0.03090245, ..., -0.07232755,
          0.02533197,  0.0144555 ],
        [ 0.03060084, -0.0062803 ,  0.04488505, ..., -0.03220448,
          0.00736146,  0.03295725],
        [ 0.06658661, -0.06630817, -0.07615933, ..., -0.07591701,
          0.08414356, -0.04627404],
        ...,
        [ 0.05902973,  0.08658428,  0.00711099, ...,  0.04378141,
          0.03084735, -0.01825583],
        [ 0.03991783, -0.04984812, -0.02444447, ..., -0.00209747,
          0.00381088,  0.05060922],
        [-0.08042001,  0.05018869, -0.07191477, ...,  0.0361343 ,
          0.00528543, -0.02457199]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(16,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(16, 16) dtype=float32, numpy=
 array([[-1.42951906e-02, -9.11821127e-02, -2.47837618e-01

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 16)                12560     
_________________________________________________________________
dense_1 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_2 (Dense)              (None, 10)                170       
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________


### N.B The default activation function of Dense Layer is LINEAR

In [9]:
model = Sequential([
      Flatten(input_shape=(28,28)),
      Dense(16, activation = "relu"),
      Dense(16, activation = "relu"),
      Dense(10),
      Softmax()
])

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 16)                12560     
_________________________________________________________________
dense_7 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_8 (Dense)              (None, 10)                170       
_________________________________________________________________
softmax (Softmax)            (None, 10)                0         
Total params: 13,002
Trainable params: 13,002
Non-trainable params: 0
_________________________________________________________________
